# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlowName', models.CharField(max_length=50)),
                ('FlowDes', models.CharField(blank=True, max_length=500)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'NOTSTART'), ('2', 'BEGINNING'), ('3', 'ENDED')], max_length=20)),
                ('rawData', models.TextField()),
                ('executeId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(blank=True, max_length=32)),
                ('ProjectDes', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relyApi', models.CharField(max_length=20)),
                ('referResultData', models.CharField(max_length=500)),
                ('referHeaderData', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='runLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runDate', models.DateTimeField()),
                ('failedOrTrue', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='sceneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sceneName', models.CharField(max_length=31)),
                ('sceneIdList', models.CharField(max_length=100)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backStage.ProjectInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SingleApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIName', models.CharField(max_length=500)),
                ('requestMethod', models.IntegerField()),
                ('requestHeaderData', models.CharField(blank=True, max_length=500)),
                ('requestSubmitMethod', models.IntegerField()),
                ('APIAddress', models.CharField(max_length=500)),
                ('requestData', models.CharField(max_length=500)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('file', models.CharField(max_length=100)),
                ('testResult', models.TextField()),
                ('testHeader', models.TextField()),
                ('failedOrTrue', models.BooleanField()),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backStage.ProjectInfo')),
            ],
        ),
        migrations.AddField(
            model_name='runlog',
            name='apiName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backStage.SingleApi'),
        ),
        migrations.AddField(
            model_name='referdata',
            name='apiName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backStage.SingleApi'),
        ),
        migrations.AddField(
            model_name='flowsheet',
            name='projectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backStage.ProjectInfo'),
        ),
    ]
